# Generated by Django 4.0.4 on 2022-08-11 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0002_alter_alumno_codigotutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='codigoTutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_alumno', to='Institucion.tutor'),
        ),
    ]
