# Generated by Django 4.0.4 on 2022-08-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0003_alter_alumno_codigotutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorarios',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
