# Generated by Django 4.0.4 on 2022-08-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institucion', '0004_alter_honorarios_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='honorarios',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
